# Generated by Django 4.2.1 on 2023-06-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, unique=True)),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('bloque', models.CharField(choices=[('A', 'Bloque A'), ('B', 'Bloque B'), ('C', 'Bloque C'), ('D', 'Bloque D'), ('E', 'Bloque E'), ('F', 'Bloque F'), ('G', 'Bloque G'), ('H', 'Bloque H'), ('I', 'Bloque I'), ('J', 'Bloque J'), ('K', 'Bloque K'), ('L', 'Bloque L'), ('M', 'Bloque M'), ('N', 'Bloque N'), ('O', 'Bloque O'), ('P', 'Bloque P'), ('Q', 'Bloque Q'), ('R', 'Bloque R'), ('S', 'Bloque S'), ('T', 'Bloque T'), ('U', 'Bloque U'), ('V', 'Bloque V'), ('W', 'Bloque W'), ('X', 'Bloque X'), ('Y', 'Bloque Y'), ('Z', 'Bloque Z')], default='A', max_length=1, null=True)),
                ('estado', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Switch',
                'verbose_name_plural': 'Switch',
                'ordering': ['nombre'],
            },
        ),
    ]
